package algorithm.comparator;

public enum EWallComparators {
    AVG_SIMILARITIES_COUNTING,
    BEST_PAIR_MATCHING,
    MUTUAL_NEAREST_NEIGHBOUR,
    LEAST_INVOLVED_BRICK_MUTUAL_NEAREST_NEIGHBOUR,
}
